### ISSUE TITLE
arg. sanitation / misspelling argument throws bad coder argument.

### ISSUE THREAD

**Issue by ewook** [soderlundf/generatewords#1]
![image](https://user-images.githubusercontent.com/2041041/67499058-b9810d00-f680-11e9-9c40-f9af837ac0d2.png)

**Comment by soderlundf** [comment]
Learn how to spell. 😂

**Comment by soderlundf** [comment]
Resolved in bb16c4f2e48ed7ccf87892c13c2d753dd9abf0ca
